# https://github.com/thijsvanloef/palworld-server-docker
version: "3.8"
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    environment:
       PORT: 8211
       PLAYERS: 16
       SERVER_PASSWORD: "worldofpals"
       MULTITHREADING: false
       RCON_ENABLED: true
       RCON_PORT: 25575
       TZ: "Asia/Bangkok"
       ADMIN_PASSWORD: "adminPasswordHere"
       COMMUNITY: false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
       SERVER_NAME: "World of Pals"
       SERVER_DESCRIPTION: "worldofpalskarn"
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    volumes:
       - ./palworld:/palworld/
